name: Run IG Publisher and Validator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
    
    - name: Setup JVM
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Download FHIR IG Publisher
      run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -O publisher.jar
    
    - name: Install Jekyll
      run: gem install jekyll --no-document
    
    - name: Build with FHIR IG Publisher
      run: java -jar publisher.jar -ig ig.ini
    
    # create ./docs folder for publishing to GitHub pages
    - name: Move to output to publish subdirectory
      run: |
          mkdir ./publish
          mv ./output ./publish/docs

    # deploy outputs to ./docs folder for publishing to GitHub pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
        enable_jekyll: true
